language: generic

services:
 - docker

env:
 - DEPENDENCY_PACKAGES="cmake desktop-file-utils intltool libaccounts-glib-dev libexif-dev libgee-0.8-dev libgeocode-glib-dev libgexiv2-dev libglib2.0-dev libgphoto2-dev libwebp-dev libgranite-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgtk-3-dev libgudev-1.0-dev libjson-glib-dev libraw-dev librest-dev libsignon-glib-dev libsoup2.4-dev libsqlite3-dev libunity-dev libwebkit2gtk-4.0-dev libxml2 librsvg2-dev python-scour valac"

install:
 - docker pull elementary/docker:loki
 - docker run -v "$PWD":/tmp/build-dir elementary/docker:loki /bin/sh -c "apt-get update && apt-get -y install $DEPENDENCY_PACKAGES && cd /tmp/build-dir && cmake . && env CTEST_OUTPUT_ON_FAILURE=true make"
 - docker pull elementary/docker:loki-unstable
 - docker run -v "$PWD":/tmp/build-dir elementary/docker:loki-unstable /bin/sh -c "apt-get update && apt-get -y install $DEPENDENCY_PACKAGES && cd /tmp/build-dir && cmake . && env CTEST_OUTPUT_ON_FAILURE=true make"

script:
 - echo BUILDS PASSED
